import { HiddenGem, CrowdReport, Badge, TravelBuddy } from "./types";

export const INITIAL_BADGES: Badge[] = [
  {
    id: "explorer-1",
    name: "First Step",
    description: "Unlocked upon your first SafarSaathi AI planning session.",
    icon: "Compass",
    color: "from-sky-400 to-sky-600",
    unlockedAt: new Date().toISOString(),
  },
  {
    id: "explorer-2",
    name: "Hidden Gem Hunter",
    description: "Discover 3 secret offbeat spots in India.",
    icon: "Gem",
    color: "from-teal-400 to-teal-600",
  },
  {
    id: "explorer-3",
    name: "Cultural Custodian",
    description: "Visit temples with full respect for local customs.",
    icon: "Flower",
    color: "from-amber-400 to-amber-600",
  },
  {
    id: "explorer-4",
    name: "Crowd Buster",
    description: "Submit a dynamic crowd alert report to save others time.",
    icon: "AlertTriangle",
    color: "from-orange-400 to-orange-600",
  },
  {
    id: "explorer-5",
    name: "Zen Nomad",
    description: "Achieve a 5-day active trip logging streak.",
    icon: "Sparkles",
    color: "from-emerald-400 to-emerald-600",
  },
  {
    id: "explorer-6",
    name: "UPI Guru",
    description: "Navigate street food zones entirely cashless.",
    icon: "Coins",
    color: "from-violet-400 to-violet-600",
  },
];

export const INITIAL_HIDDEN_GEMS: HiddenGem[] = [
  {
    id: "gem-1",
    name: "Mawlynnong Village, Meghalaya",
    region: "East Khasi Hills, Meghalaya",
    category: "Quaint Village",
    description: "Acclaimed as Asia's cleanest village. Features bamboo dustbins every few meters, pristine living root bridges nearby, and a remarkable preservation of local Khasi customs.",
    photographyTime: "Morning (7:00 AM - 9:00 AM) for soft tropical mist shots.",
    localSecret: "Climb the Sky View bamboo tower for views extending into the plains of Bangladesh.",
    scamWarning: "Avoid local guides who demand hefty fees for crossing root bridges; they are free to traverse.",
    upiAvailability: "Limited. Carry cash for tea stalls and local entry fees.",
    lat: 25.2016,
    lng: 91.9048,
  },
  {
    id: "gem-2",
    name: "Lonar Crater Lake, Maharashtra",
    region: "Buldhana District, Maharashtra",
    category: "Panoramic Viewpoint",
    description: "The world's only hyper-velocity impact crater formed in basalt rock, holding a unique alkaline-saline lake. Surrounded by ancient temples from the 12th century.",
    photographyTime: "Sunset (5:30 PM) from the Dhar Temple viewpoint.",
    localSecret: "The water level drops in May, revealing salt deposits and ancient carvings hidden on the banks.",
    scamWarning: "Ignore self-proclaimed geologists charging for 'meteorite stone samples'; they are regular basalt.",
    upiAvailability: "Fully Available in Lonar town, limited near the lake base.",
    lat: 19.9760,
    lng: 76.5073,
  },
  {
    id: "gem-3",
    name: "Gurez Valley, Kashmir",
    region: "Bandipora, Jammu & Kashmir",
    category: "Secret Waterfall",
    description: "An incredibly beautiful valley sitting along the ancient Silk Route. Surrounded by snow-clad peaks, pine forests, and the sparkling blue waters of the Kishanganga river.",
    photographyTime: "Early Afternoon (12:00 PM - 2:00 PM) when the Habba Khatoon peak reflects on the river.",
    localSecret: "Visit the tiny waterfall of Gurez-base near Dawar; locals consider its water extremely sweet.",
    scamWarning: "Register your entry at military checkpoints yourself. Never pay third parties to speed up checks.",
    upiAvailability: "Cash Recommended. Mobile network drops frequently.",
    lat: 34.6342,
    lng: 74.8398,
  },
  {
    id: "gem-4",
    name: "Gandikota Gorge, Andhra Pradesh",
    region: "Kadapa District, Andhra Pradesh",
    category: "Panoramic Viewpoint",
    description: "Popularly known as the 'Grand Canyon of India'. The Pennar River winds through majestic red granite gorge walls, overlooked by a historic 12th-century Gandikota Fort.",
    photographyTime: "Sunrise (5:45 AM) for red canyon glowing effect.",
    localSecret: "Walk behind the Madhavaraya Temple at dusk for a completely solitary view of the river gorge.",
    scamWarning: "Campsite vendors may inflate dinner prices. Book camping guides only via verified State Tourism agents.",
    upiAvailability: "Fully Available at fort entry and registered campsites.",
    lat: 14.8111,
    lng: 78.2862,
  },
  {
    id: "gem-5",
    name: "Ziro Valley, Arunachal Pradesh",
    region: "Lower Subansiri, Arunachal Pradesh",
    category: "Quaint Village",
    description: "Home of the friendly Apatani tribe, famous for their unique sustainable agriculture, handloom weaving, and facial tattoos. Surrounded by rich pine hills.",
    photographyTime: "Morning golden hour over the layered wet paddy fields.",
    localSecret: "Visit the organic Kiwi orchards in Hong village and taste home-brewed rice beer ('Apong').",
    scamWarning: "Tribal photography is highly sensitive. Always ask for polite permission. Never pay random children to pose.",
    upiAvailability: "Limited. Keep BSNL/Jio SIMs as back-up.",
    lat: 27.5956,
    lng: 93.8315,
  }
];

export const INITIAL_CROWD_REPORTS: CrowdReport[] = [
  {
    id: "report-1",
    place: "Kedarnath Temple, Uttarakhand",
    crowdLevel: "Overcrowded",
    queueTimeMinutes: 240,
    parkingStatus: "Full",
    comment: "Extremely long queue starting from the bridge. Registration QR codes are checked strictly. Highly recommend taking the token early morning at 4:00 AM.",
    reporterName: "Rajesh K.",
    timestamp: new Date(Date.now() - 3600000 * 2).toISOString(), // 2 hours ago
  },
  {
    id: "report-2",
    place: "Taj Mahal, Agra",
    crowdLevel: "Moderate",
    queueTimeMinutes: 45,
    parkingStatus: "Limited",
    comment: "Sunrise queue at East Gate is moving fast. Shoe cover counters are crowded, carry yours in hand. Ticket online QR works instantly.",
    reporterName: "Priya Sharma",
    timestamp: new Date(Date.now() - 3600000 * 4).toISOString(), // 4 hours ago
  },
  {
    id: "report-3",
    place: "Tirumala Balaji Darshan, AP",
    crowdLevel: "Crowded",
    queueTimeMinutes: 180,
    parkingStatus: "Full",
    comment: "Special Entry Darshan (300 Rs) took about 3 hours. Cell phones must be submitted at the main locker room before the Vaikuntam queue complex.",
    reporterName: "Ananth S.",
    timestamp: new Date(Date.now() - 3600000).toISOString(), // 1 hour ago
  },
  {
    id: "report-4",
    place: "Fort Aguada, Goa",
    crowdLevel: "Low",
    queueTimeMinutes: 5,
    parkingStatus: "Available",
    comment: "Peaceful visit. Wind is pleasant. Carry umbrellas for sun cover. UPI ticket machine near entry is working perfectly.",
    reporterName: "Rohit Deshmukh",
    timestamp: new Date(Date.now() - 3600000 * 6).toISOString(),
  }
];

export const INITIAL_TRAVEL_BUDDIES: TravelBuddy[] = [
  {
    id: "buddy-1",
    name: "Aarav Mehta",
    age: 24,
    location: "Mumbai",
    style: "Backpacker / Trekker",
    destination: "Kasol & Spiti Valley",
    dates: "Aug 10 - Aug 22, 2026",
    bio: "Software developer on workation. Love trekking, playing acoustic guitar around the bonfire, and exploring lesser-known villages. Looking for fellow budget nomads to pool cabs!",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=200",
  },
  {
    id: "buddy-2",
    name: "Sneha Nair",
    age: 27,
    location: "Bengaluru",
    style: "Cultural / Food Explorer",
    destination: "Rajasthan (Jaipur-Jodhpur)",
    dates: "Sep 04 - Sep 12, 2026",
    bio: "Photographer and foodie. Want to try every royal thali and capture sunset shots at forts. Traveling solo, would love to join up with other female travelers for safety and fun!",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200",
  },
  {
    id: "buddy-3",
    name: "Kabir Das",
    age: 31,
    location: "Delhi",
    style: "Adventure / Biker",
    destination: "Leh Ladakh Highway",
    dates: "Jul 20 - Aug 02, 2026",
    bio: "Biking enthusiast doing the classic Manali-Leh circuit. Have standard gear, spare tubes, and basic mechanical knowledge. Looking for rider buddies to convoy safely.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200",
  }
];
